
[[headers]]
  for = "/*.png"
    [headers.values]
      Cache-Control = "max-age=7776000, public"

[[headers]]
  for = "/*.jpg"
    [headers.values]
      Cache-Control = "max-age=7776000, public"

[[headers]]
  for = "/*.jpeg"
    [headers.values]
      Cache-Control = "max-age=7776000, public"

[[headers]]
  for = "/*.gif"
    [headers.values]
      Cache-Control = "max-age=7776000, public"
