# netlify.toml

# Caching settings
[[headers]]
  for = ["*.js", "*.css"]
    [headers.values]
      Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = ["*.jpg", "*.jpeg", "*.png", "*.gif", "*.svg"]
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
